# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmPRjGpk5P7CyqdddAMfa0C-5veRSmc-

data visualisation

importing library
"""

import matplotlib.pyplot as plt

"""to make blank space

we assign same thing for both means one figure&only one subplot
"""

fig,ax=plt.subplots()

"""figure 1 and plot 2"""

fig,ax=plt.subplots(nrows=2)

"""figure1 and plot 4"""

fig,ax=plt.subplots(nrows=2,ncols=2,figsize=(15,10))

x=[1,2,3,4,5,6,7,8,9,10]
y=[11,18,13,14,19,11,24,15,11,11]

fig,ax=plt.subplots()

ax.bar(x,y)

"""ax.plot--linegraph,
ax.bar----bargraph,
ax.hbar----horizontalbargraph,
ax.scatter---scattergraph,
ax.pie-----piechart,
ax.hist-----histogram,

"""

fig,ax=plt.subplots()


ax.plot(x,y)

fig,ax=plt.subplots()

ax.barh(x,y)

fig,ax=plt.subplots()

ax.scatter(x,y)

""";----we use semicolumn to remove text
or we can use plt.show
"""

fig,ax=plt.subplots()

ax.pie(y)

fig,ax=plt.subplots()

ax.pie(y);

fig,ax=plt.subplots()

ax.pie(y)
plt.show()

fig,ax=plt.subplots()

ax.hist(y)

"""Advance Matplotlib"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("https://github.com/YBI-foundation/Dataset/raw/main/Tips.csv")

df.head()

"""making graph from dataframe

ax.scatter("col1","col2",data=dataframe_name)

1 way to use dataframe---seaborn also use this way
"""

fig,ax=plt.subplots()
ax.scatter("total_bill","tip",data=df)

"""defing with dataframe

2 way of using dataframe
"""

fig,ax=plt.subplots()
ax.scatter(df["total_bill"],df["tip"])

fig,ax=plt.subplots()
ax.bar("day","total_bill",data=df)

fig,ax=plt.subplots()
ax.barh(df["day"],df['total_bill'])

fig,ax=plt.subplots()
ax.pie("size",data=df);

"""visualisaton in more subplots

ax[address],address=row,col
"""

fig,ax=plt.subplots(nrows=2,ncols=2)
ax[1,1].scatter('total_bill',"tip",data=df)
ax[0,1].bar('day',"total_bill",data=df)

"""note=data can be from diffrent dataframe or tables

multiple graph or chart can be used in single sublot
"""

fig,ax=plt.subplots(nrows=2,ncols=2)
ax[1,1].scatter('total_bill',"tip",data=df)
ax[1,1].bar('total_bill',"tip",data=df)
ax[0,1].bar('day',"total_bill",data=df)
ax[0,0].barh("day","total_bill",data=df)
ax[1,0].pie(df["size"]);

"""seaborn-----statical data visualisation

"""

import seaborn as sns

df

sns.pairplot(df)

"""there are two types of variable
1--categorical
2--numerical

categorial---sex,days,smoker,time

hue is just another name for color

---

hue keyword used for diffentiate using colors in categorial data
"""

sns.pairplot(df,hue="smoker")

sns.pairplot(df,hue="day")

